unified processing error log [2]
PasteUs/PasteMeJavaBackend pull request #10
Opened 2019-11-27 15:08 UTC by 1059438020

2019-12-01 11:29 UTC, LucienShui requested changes

2019-12-01 11:29 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +                times --;
这里不需要有空格。

2019-12-01 11:29 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +        @NotBlank String key = util.token2Key(token);
这里的 `@NotBlank` 貌似不会起作用。

2019-12-01 11:29 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> + * @author Lucien, Moyu
最近修改过的人的名字在最左边。

2019-12-01 11:29 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +    }
元佬指出这里最好带上 `@Autowired`
```java
public PasteServiceImpl(@Autowired Checker checker,
                        @Autowired TemporaryManager temporaryManager,
                        @Autowired PermanentManager permanentManager,
                        @Autowired ManagerCreateFactory managerCreateFactory) {
        this.checker = checker;
        this.temporaryManager = temporaryManager;
        this.permanentManager = permanentManager;
        this.managerCreateFactory = managerCreateFactory;
    }
```

2019-12-01 11:29 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +            throw new GlobalException(ResponseCode.PARAM_ERROR);
我觉得 `Exception` 最好还是不要太笼统。

2019-12-01 11:29 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +                                            HttpServletRequest httpServletRequest) throws Exception {
具体一下 `Exception` 的类型。

2019-12-01 11:29 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +                                            HttpServletRequest httpServletRequest) throws Exception {
现在 manager 会抛异常吗？如果没有的话就先把不同的 `Exception` 写在 backend 里就行。

2019-12-01 11:29 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/util/factory/manager/ManagerCreateFactory.java
> +public class ManagerCreateFactory {
直接叫 `ManagerFactory` 就可以。

2019-12-01 11:29 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +                throw new Exception("The key are repeated");
应该是单数吧，换成 `Duplicate key` 好了。

2019-12-01 12:06 UTC, 1059438020 commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +        @NotBlank String key = util.token2Key(token);
@NotBlank 如果我没记错的话应该是配合 @Valid 去做接口参数校验的，不能在这个情景下用吧

2019-12-01 12:11 UTC, 1059438020 commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +    }
这里是担心有多个构造函数造成无法注入的问题吗

2019-12-01 12:13 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +    }
貌似写在这里是给读代码的人看的。

2019-12-01 12:14 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +        @NotBlank String key = util.token2Key(token);
既然你知道，还加上干啥...

2019-12-01 12:15 UTC, 1059438020 commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +        @NotBlank String key = util.token2Key(token);
这个我只是把 try catch 去了，里面的逻辑我没动

2019-12-01 12:17 UTC, 1059438020 commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +            throw new GlobalException(ResponseCode.PARAM_ERROR);
是要打印这样的日志吗
log.error("token = {}, exception = ", token, e);
还是要有详细的 ResponseCode

2019-12-01 12:17 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +        @NotBlank String key = util.token2Key(token);
🤯尴尬，原来是我写的，顺手改一下吧...

2019-12-01 12:19 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +            throw new GlobalException(ResponseCode.PARAM_ERROR);
不是，比如说 `throw new ParamErrorException`，或者是 `throw new DuplicateException` 这样子，用不同的 `Exception` 子类去区分。

2019-12-01 12:25 UTC, 1059438020 commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +            throw new GlobalException(ResponseCode.PARAM_ERROR);
```java
public class GlobalExceptionHandler {
    @ExceptionHandler(value = Exception.class)
    public static Response exceptionHandler(Exception e) {
        if (e instanceof GlobalException) {
            GlobalException ge = (GlobalException) e;
            return Response.error(ge.getResponseCode());
        } else if (e instanceof org.springframework.validation.BindException) {
            List<ObjectError> errors = ((BindException) e).getAllErrors();
            ObjectError error = errors.get(0);
            String msg = error.getDefaultMessage();
            return Response.error(ResponseCode.BIND_ERROR.fillArgs(msg));
        } else {
            return Response.error(ResponseCode.SERVER_ERROR);
        }
    }
}
```
之前的全局异常处理是这样的，如果返回的是具体 Exception，ResponseCode 会全都是 Server Error。这个地方如果有需求的话可能得稍微改一下全局异常处理，得加个策略模式之类的

2019-12-02 01:09 UTC, LucienShui approved these changes

2019-12-02 01:10 UTC, merged

2019-12-02 05:22 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/controller/Controller.java
> +            throw new GlobalException(ResponseCode.PARAM_ERROR);
这个 有没有更优雅一点的写法？这么写开闭原则搞不定啊( 未来有变动又得改代码

2019-12-02 05:33 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +
这个随机码生成器还是比较有趣的 如果担心重复，我建议用UUID或者其他的保证无冲突的随机码生成会更好，这个100次重试越到后面越不靠谱

2019-12-02 05:33 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +        if (pasteDTO.getKey() == null || pasteDTO.getKey().isBlank()) {
我记得有个东西叫做ObjectUtil,代替这个判断会好用的多。可以看看这些工具类的源码

2019-12-02 05:33 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +        String key = null;
key没初始化的时候就是null, 可以不用写出来

2019-12-02 05:33 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +        throw new ManipulationException("Create permanent failed");
如果创建失败，是否可以收集一波错误信息便于排错？

2019-12-02 05:33 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/util/factory/manager/ManagerFactory.java
> +    public PasteManager getPasteManager(String key) {
我的建议是，暴露这些manager的原型，在外部调用get set做到无感知，省去手动getManager这个过程。看到上面对这个类的使用方式，不是很优雅

2019-12-02 06:08 UTC, LucienShui commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +
这里我在写 golang 部分的时候有做过尝试，想生成 8 位的 uuid 比较难，如果生成一个 normal uuid 再截取前 8 位还是会冲突的。

2019-12-02 06:51 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/service/impl/PasteServiceImpl.java
> +
短UUID的话，有挺多实践的。说不定可以看看这个[shortuuid](https://github.com/skorokithakis/shortuuid)