get Service,有冲突，做了暂时处理，关于返回类型有分歧
PasteUs/PasteMeJavaBackend pull request #4
Opened 2019-10-01 19:06 UTC by 1059438020

2019-10-02 05:19 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/BackendApplication.java
> +@ComponentScan("cn.pasteme.*")
@ComponentScan在其他文件有了，不需要再加

2019-10-02 05:20 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/controller/DemoController.java
> +    public DemoController(DemoService demoService, PasteService pasteService) {
如果是要注入，可以直接用
@Autowire
private PasteService pasteService;
不需要每次都更改构造函数

2019-10-02 05:21 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/controller/DemoController.java
> +    public Result getPaste(@PathVariable String key,
建议分成两个函数，不需要都绑在一个函数上，违反单一职责模式

2019-10-02 05:26 UTC, ryanlee2014 commented on src/main/java/cn/pasteme/backend/controller/DemoController.java
> +    public Result customTemp(@PathVariable String key,
建议加一个动词，达到方法名语义化

2019-10-02 05:28 UTC, ryanlee2014 reviewed
Service层的作用要不讨论一下？这个Controller和Service我没看出来要写什么东西

2019-10-03 17:57 UTC, LucienShui requested changes
CodeFactor

2019-10-25 07:30 UTC, LucienShui commented
outdate

2019-10-25 07:30 UTC, closed without merging